
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  h2:
    console:
      enabled: true
  thymeleaf:
  # thymeleaf 참조 경로
    prefix: classpath:/templates/
    suffix: .html
  # thymeleaf에 대한 캐시를 남기지 않는다. cache=false 설정(운영시는 true)
    cache: false

logging:
  level:
    org.hibernate.sql: debug
##    show_sql true 설정의 쿼리에 ? 에 파라미터를 보고싶으면 아래 설정을 추가해주면 된다
#    org.hibernate.type: trace